env:
    node: true
root: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - prettier
    - plugin:import/recommended
    - plugin:import/typescript
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: latest
plugins:
    - '@typescript-eslint'
rules:
    sort-imports:
        - error
        - ignoreCase: false
          ignoreDeclarationSort: true
          ignoreMemberSort: false
          memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single']
          allowSeparatedGroups: true

    import/no-unresolved: error
    import/order:
        - error
        - groups:
              - builtin
              - external
